// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyfwlytwurfmwmmhmdov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5ZndseXR3dXJmbXdtbWhtZG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDcwNzcsImV4cCI6MjA3NDcyMzA3N30.e_GGZoh88lQrtdhe5eRNxTnSiGrV77VArPmuTmhmErI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});